account_id = "9f4998a66a5d7bd7a230d0222544fbe6"
name = "baas-api"
main = "apps/baas-api/worker.js"
compatibility_date = "2023-10-30"

[[d1_databases]]
binding = "DB"
database_name = "baas-db"
database_id = "e1ac45c9-fe10-4a08-8ca6-6e83be14b74b"

[vars]
PUBLIC_BASE_URL = "__YOUR_WORKER_URL__" # TODO: Replace with your worker URL
ALLOWED_ORIGINS = "__YOUR_APP_ORIGINS__" # TODO: Replace with your app's origins (comma-separated)
